DROP TABLE IF EXISTS MOEDA;
DROP TABLE IF EXISTS COTACAO;

CREATE TABLE MOEDA (
ID_MOEDA INT AUTO_INCREMENT PRIMARY KEY,
TX_NOME VARCHAR(50) NOT NULL,
TX_SIMBOLO VARCHAR(5) NOT NULL
);

CREATE TABLE COTACAO (
ID_COTACAO INT AUTO_INCREMENT PRIMARY KEY,
ID_MOEDA INT NOT NULL,
DT_DATA DATE NOT NULL,
VR_VALOR DECIMAL(14,4)
);
